### ISSUE TITLE
I'm looking to obtain the database and glyph images of Charbase.com

### ISSUE THREAD

**Issue by Cyberider** [matwagner/EncodingCollector#1]
Is this what the goal of your project is?
If yes, can you somehow access and use the data and glyph images from [Charbase.com](http://www.charbase.com)?
I have been searching for a UTF-8 dataset that contains all the data found at Charbase.

**Comment by matwagner** [comment]
The goal of the project is to get converter functions for encodings from GNU libiconv to convert to or from Unicode encodings. It lists nearly all the encodings from the specified data sources. GNU libiconv doesn't support them all.

Individual glyphs are not part of the project. They can be obtained from Unicode in its Codepoint Charts or on charbase.com which seems to be outdated.
